version: "3"
services:
  server:
    image: docker.io/kyoheiudev/hmstr-server:0.2.0
    container_name: server
    volumes:
      - ./server/databases:/var/hmstr/databases
    ports:
      - 8000:8000
  client:
    build: client
    container_name: client
    ports:
      - 3000:3000
